name: CI

env:
    CI: true

on: [push]

jobs:
    build-test:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: ['ubuntu-latest']
                php-versions: ['8.1']

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }})

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Libraries
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                       sudo apt-get install pdftk wkhtmltopdf ghostscript imagick cpdf
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                       brew install pdftk wkhtmltopdf ghostscript imagick cpdf
                  fi
              shell: bash

            - name: PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  extensions: gd
                  tools: composer, phpunit

            - name: Composer
              run: composer install --no-interaction

            - name: PHPUnit
              run: ./vendor/bin/phpunit
